[project]
name = "datacommons-mcp"
dynamic = ["version"]
description = "Data Commons MCP server."
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "fastapi==0.119.1",
    "uvicorn==0.38.0",
    "fastmcp==2.12.5",
    "requests==2.32.5",
    "datacommons-client==2.1.3",
    "pydantic==2.12.3",
    "pydantic-settings==2.11.0",
    "python-dateutil==2.9.0.post0",
    "requests-mock==1.12.1",
]
urls = {Homepage = "https://github.com/datacommonsorg/agent-toolkit"}

[project.scripts]
datacommons-mcp = "datacommons_mcp.cli:cli"

[build-system]
requires = ["uv", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["datacommons_mcp*"]

[tool.setuptools.package-data]
datacommons_mcp = ["**/*.json"]

[tool.setuptools.dynamic]
version = {attr = "datacommons_mcp.version.__version__"}
